name: VPS Handle

on:

# Dispara manualmente
  workflow_dispatch:


# Dispara quando tem push na main
  push:
    branches:
      - "main"

permissions:
  contents: read

# Não permite duas execuções ao mesmo tempo
concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  say-hello-on-vps:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - name: Execute echo Hello on VPS
        uses: appleboy/ssh-action@b838bc2f27cd449b957159452d432aff91697637 # v1.2.5
        with:
          host: ${{ secrets.HOST_HOSTINGER }}
          username: ${{ secrets.USERNAME_KRAB }}
          key: ${{ secrets.VPS_SSH_KEY_HOSTINGER }}
          script: echo "Hello World"

      - name: Debug Host Size
        run: echo "Tamanho da chave é ${{ strlen(secrets.HOST_HOSTINGER) }}"

      - name: Debug Username Size
        run: echo "Tamanho da chave é ${{ strlen(secrets.USERNAME_KRAB) }}"

      - name: Debug Secret Size
        run: echo "Tamanho da chave é ${{ strlen(secrets.VPS_SSH_KEY_HOSTINGER) }}"
